### ISSUE TITLE
help for ubuntu

### ISSUE THREAD

**Issue by juancubas** [milkey-mouse/JSSCC#2]
im new in this type of things, and im using ubuntu with firefox and the program dont let me drop  the midi file into the browser, what i can do?
first time using hithub, and sorry for my english

**Comment by cole36912** [comment]
I don't think the player was ever implemented, and it seems abandoned now.

**Comment by twilligon** [comment]
that's more or less correct: https://github.com/milkey-mouse/JSSCC/issues/4#issuecomment-414027589
