### ISSUE TITLE
jsscc github.io page broken for chrome

### ISSUE THREAD

**Issue by stt** [milkey-mouse/JSSCC#3]
When drag-n-dropping .mid file console prints `Refused to execute script from 'https://cdn.rawgit.com/nfroidure/MIDIFile/master/dist/MIDIFile.js' because its MIME type ('') is not executable, and strict MIME type checking is enabled.`

**Comment by twilligon** [comment]
Hmm. I thought the whole point of [RawGit](https://rawgit.com/) was to set the MIME type correctly? 🤔

**Comment by stt** [comment]
Yep, didn't look into it any further than that .. now having a better look, the actual issue is that nfroidure repo doesn't have `dist`dir anymore. Including this in jsscc instead should fix it? https://rawgit.com/nfroidure/midifile/master/src/MIDIFile.js
